### ISSUE TITLE
Error fetching remote state

### ISSUE THREAD

**Issue by Seopril** [tombeynon/easy-0l-miner#1]
I receive the following error when running docker-compose up -d and inspecting the logs with docker-compose logs -f:

```
miner_1  | Mining VDF Proof # 14
miner_1  | Delay: 1814 seconds
miner_1  | Proof mined: proof_14.json created.
miner_1  | Fetching remote tower height: http://176.57.189.120:8080/, 733C4CAA99F3FA11DDDC80F27D014344
miner_1  | Remote tower height: -1
miner_1  | Local tower height: 14
miner_1  | Backlog: resubmitting missing proofs.
miner_1  | submitting proof 0
miner_1  | ERROR: Failed fetching remote state, message: Error { inner: Inner { kind: JsonRpcError, source: None, json_rpc_error: Some(JsonRpcError { code: -32003, message: "Server error: VM Invariant violation error: UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION", data: Some(StatusCode(UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION)) }) } }
```

The ERROR portion occurs with every proof generated, including the genesis proof.

I'm using the docker-compose based on the README. The node IP I'm using is 176.57.189.120. The underlying OS is Ubuntu 20.10.

**Comment by tombeynon** [comment]
If I recall, this error happens if the wallet hasn't been onboarded yet? You would need to be onboarded as per https://github.com/OLSF/libra/blob/main/ol/documentation/node-ops/tower_mining_VDF_proofs.md#check-if-an-account-needs-to-be-created

This can also be done in the Carpe app. Let me know if this was the issue and I'll make sure to add something to the docs

**Comment by Seopril** [comment]
I just onboarded the account and it appears to be submitting the transactions successfully now. Thanks for the support!
